version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api

    django: &django
        build: 
            context: ./api
        image: shydro_django
        depends_on:
            - postgres
        volumes:
            - .:/code
        ports:
            - "8000:8000"
    redis:
        image: redis:3.2

    celeryworker:
        <<: *django
        image: cride_local_celeryworker
        depends_on:
        - redis
        - postgres
        
        ports: []

    celerybeat:
        <<: *django
        image: cride_local_celerybeat
        depends_on:
        - redis
        - postgres
        
        ports: []

    flower:
        <<: *django
        image: cride_local_flower
        ports:
        - "5555:5555"
    #react:
    #    build: ./ui_crm
    #    image: shydro_react
    #    ports:
    #        - "4200:80"
    #    depends_on:
    #        - django
    #        - postgres

    #react_bramadero:
    #    build: ./views_data/bramadero
    #    image: bramadero_dash
    #    ports:
    #        - "4300:80"
    #    depends_on:
    #        - django
    #        - postgres


    #react_cardal:
    #    build: ./views_data/cardal_alto_bajo
    #    image: cardal_dash
    #    ports:
    #        - "4301:80"
    #    depends_on:
    #        - django
    #
