version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
services:
    postgres:
        image: postgres:12
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api
            PGDATA: /data/postgres

    django: &django
        build: ./api 
        image: shydro_django
        depends_on:
            - postgres
        volumes:
            - .:/code
        ports:
            - "8000:8000"

    #cron:
    #    build: ./api     # same as main application
    #    restart: unless-stopped
    #    image: cron_smarthydro
    #    volumes:
    #        - .:/code
    #    depends_on:
    #        - postgres
    #        - django
    #    command: cron -f  # as a long-running foreground process
    
    #react_crm:
    #    build: ./ui_crm
    #    image: crm
    #    ports:
    #        - "4200:80"
    #    depends_on:
    #        - django
    #        - postgres

    #react_prototype:
    #    build: ./ui_sh_prototype
    #    image: ui_prorotype
    #    ports:
    #        - "4201:80"
    #    depends_on:
    #        - django
    #        - postgres
    
    #react_web:
    #    build: ./landing_sh
    #    image: web
    #    ports:
    #        - "80:80"
    #    depends_on:
    #        - django
    #        - postgres





    
