version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    certs: {}
    vhostd: {}
    html: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api

    nginx_proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - certs:/etc/nginx/certs:ro
          - vhostd:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
          - NGINX_PROXY_CONTAINER=nginx_proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - nginx_proxy


    django: &django
        build: ./api
        image: shydro_django
        volumes:
            - .:/code
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=api.smarthydro.cl, www.api.smarthydro.cl
            - LETSENCRYPT_HOST=api.smarthydro.cl, www.smarthydro.cl
            - LETSENCRYPT_EMAIL=api@smarthydro.cl

        depends_on:
            - nginx_proxy
            - letsencrypt
            - postgres 


    react_landing:
        build: ./landing_sh
        image: landing
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=smarthydro.cl, www.smarthydro.cl
            - LETSENCRYPT_HOST=smarthydro.cl, www.smarthydro.cl
            - LETSENCRYPT_EMAIL=app@amamaule.cl
        depends_on:
            - django
            - nginx_proxy
            - letsencrypt

    react_crm:
        build: ./ui_crm
        image: crm
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=crm.smarthydro.cl, www.crm.smarthydro.cl
            - LETSENCRYPT_HOST=crm.smarthydro.cl, www.crm.smarthydro.cl
            - LETSENCRYPT_EMAIL=app@amamaule.cl
        depends_on:
            - django
            - nginx_proxy
            - letsencrypt
    
    react_prototype:
        build: ./ui_sh_prototype
        image: ui_prorotype
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=dataiot.smarthydro.cl, www.dataiot.smarthydro.cl
            - LETSENCRYPT_HOST=dataiot.smarthydro.cl, www.dataiot.smarthydro.cl
            - LETSENCRYPT_EMAIL=app@amamaule.cl
        depends_on:
            - django
            - nginx_proxy
            - letsencrypt







