version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_new: {}
    local_postgres_data_backups: {}
    certs: {}
    vhostd: {}
    html: {}

services:
    postgres:
        image: postgres:15
        volumes:
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api
            PGDATA: /data/postgres

    nginx_proxy:
        image: jwilder/nginx-proxy       
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - certs:/etc/nginx/certs:ro
          - vhostd:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
          - NGINX_PROXY_CONTAINER=nginx_proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - nginx_proxy


    django: &django
        build: ./api
        image: shydro_django
        volumes:
            - .:/code
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=api.smarthydro.app, www.api.smarthydro.app
            - LETSENCRYPT_HOST=api.smarthydro.app, www.api.smarthydro.app
            - LETSENCRYPT_EMAIL=api@smarthydro.app

        depends_on:
            - nginx_proxy
            - letsencrypt
            - postgres 

    cron:
        build: ./api     # same as main application
        restart: unless-stopped
        image: cron_smarthydro
        volumes:
          - .:/code
        depends_on:
          - postgres
          - django
        command: cron -f  # as a long-running foreground process

    react_prototype:
        build: ./ui_ikolu
        image: ui_new
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=ikolu.smarthydro.app, www.ikolu.smarthydro.app
            - LETSENCRYPT_HOST=ikolu.smarthydro.app, www.ikolu.smarthydro.app
            - LETSENCRYPT_EMAIL=app@smarthydro.app
        depends_on:
            - django
            - nginx_proxy
            - letsencrypt
