# Generated by Django 4.2.4 on 2024-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='name_client',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
