# Generated by Django 4.2.4 on 2024-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_profileclient_name_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableclient',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
