# Generated by Django 4.2.4 on 2024-03-27 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_variableclient_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactiondetail',
            options={'verbose_name': 'Registro telemetria', 'verbose_name_plural': 'Registros Telemetria'},
        ),
        migrations.AlterModelOptions(
            name='profileclient',
            options={'verbose_name': 'Punto de captacion', 'verbose_name_plural': 'Puntos de captacion'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='variableclient',
            options={'verbose_name': 'Variable', 'verbose_name_plural': 'Puntos de captacion - Variables'},
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='code_dga_site',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Codigo de obra(dga)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='d1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profundidad(mt)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='d2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posicionamiento de bomba(mt)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='d3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posicionamiento nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='d4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diametro ducto salida bomba(pulg)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='d5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diametro flujometro(pulg)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='date_delivery_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha acta de entrega'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='date_monitoring',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio monitoreo'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='date_reporting_dga',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio transmision DGA'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='flow_granted_dga',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Caudal otorgado'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_apr',
            field=models.BooleanField(default=False, verbose_name='Es APR'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_dga',
            field=models.BooleanField(default=False, verbose_name='Es DGA'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_monitoring',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activar monitoreo'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_prom_flow',
            field=models.BooleanField(default=False, verbose_name='Es caudal promedio'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_send_dga',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activar envio de datos a DGA'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_thethings',
            field=models.BooleanField(default=False, verbose_name='Es Nettra'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='module_1',
            field=models.BooleanField(default=True, verbose_name='MODULO: Mi Pozo'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='module_2',
            field=models.BooleanField(default=False, verbose_name='MODULO: DGA'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='module_3',
            field=models.BooleanField(default=False, verbose_name='MODULO: Datos y reportes'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='module_4',
            field=models.BooleanField(default=False, verbose_name='MODULO: Graficos'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='module_5',
            field=models.BooleanField(default=False, verbose_name='MODULO: Indicadores'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='name_client',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='password_dga_software',
            field=models.CharField(default='ZSQgCiDg7y', max_length=1400, verbose_name='clave DGA'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='qr_dga',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='rut_report_dga',
            field=models.CharField(default='17352192-8', max_length=1400, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='scale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Escala(lt*pulsos)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='standard',
            field=models.CharField(blank=True, choices=[('MAYOR', 'mayor'), ('MEDIO', 'medio'), ('MENOR', 'menor'), ('CAUDALES_MUY_PEQUENOS', 'caudales_muy_pequenos')], max_length=300, null=True, verbose_name='Estandar'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='type_dga',
            field=models.CharField(blank=True, choices=[('SUB', 'subterraneo'), ('SUP', 'superficial')], default='SUB', max_length=300, null=True, verbose_name='Captacion'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contador(solo aplica a totalizadores)'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='is_other_token',
            field=models.BooleanField(default=False, verbose_name='Utiliza su propio Token'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='is_other_url',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Servicio web diferente'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_profile', to='crm.profileclient', verbose_name='Punto de captacion'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='service',
            field=models.CharField(blank=True, choices=[('NOVUS', 'novus'), ('THETHINGS', 'thethings')], max_length=1200, null=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='str_variable',
            field=models.CharField(max_length=400, verbose_name='Variable logger/MQTT'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='token_service',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Token de variable'),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='type_variable',
            field=models.CharField(choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('ACUMULADO', 'acumulado')], max_length=1200, verbose_name='Tipo variable'),
        ),
    ]
