# Generated by Django 4.0.3 on 2022-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200812_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('project_code', models.CharField(blank=True, max_length=400, null=True)),
                ('date_medition', models.DateField(blank=True, max_length=300, null=True)),
                ('measurement_time', models.DurationField(blank=True, null=True)),
                ('flow', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('nivel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
