# Generated by Django 4.0.4 on 2022-05-12 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_interactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('token_service', models.CharField(blank=True, max_length=400, null=True)),
                ('d1', models.CharField(blank=True, max_length=100, null=True)),
                ('d2', models.CharField(blank=True, max_length=100, null=True)),
                ('d3', models.CharField(blank=True, max_length=100, null=True)),
                ('d4', models.CharField(blank=True, max_length=100, null=True)),
                ('d5', models.CharField(blank=True, max_length=100, null=True)),
                ('d6', models.CharField(blank=True, max_length=100, null=True)),
                ('scale', models.IntegerField(blank=True, max_length=100, null=True)),
                ('in1', models.BooleanField(blank=True, default=True)),
                ('in2', models.BooleanField(blank=True, default=True)),
                ('in3', models.BooleanField(blank=True, default=True)),
                ('in4', models.BooleanField(blank=True, default=True)),
                ('in5', models.BooleanField(blank=True, default=True)),
                ('in6', models.BooleanField(blank=True, default=True)),
                ('others_ind', models.BooleanField(blank=True, default=False)),
                ('qr_dga', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_apr', models.BooleanField(blank=True, null=True)),
                ('is_dga', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.profileclient')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataHistoryFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('month', models.CharField(blank=True, max_length=300, null=True)),
                ('production', models.IntegerField(blank=True, null=True)),
                ('billing', models.IntegerField(blank=True, null=True)),
                ('constant_a', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.profileclient')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('profiles', models.ManyToManyField(blank=True, related_name='admin_view_profiles', to='crm.profileclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
