# Generated by Django 4.2.4 on 2024-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_interactiondetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableclient',
            name='convert_to_lt',
            field=models.BooleanField(default=False, verbose_name='Pasar a lt(solo aplica en caudal)'),
        ),
    ]
