# Generated by Django 4.2.4 on 2024-04-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_variableclient_convert_to_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileclient',
            name='date_monitoring',
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='date_time_medition',
            field=models.DateTimeField(blank=True, max_length=800, null=True, verbose_name='Fecha/hora medicion'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='flow',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Caudal(lt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='is_send_dga',
            field=models.BooleanField(default=False, verbose_name='DGA'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='nivel',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='profile_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.profileclient', verbose_name='Punto de captacion'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='total',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Total(m3)'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_prom_flow',
            field=models.BooleanField(default=False, verbose_name='Caudal promedio'),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='is_send_dga',
            field=models.BooleanField(blank=True, null=True, verbose_name='Envio DGA'),
        ),
    ]
