# Generated by Django 4.0.4 on 2022-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_profileclient_registerpersons_datahistoryfact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='theme',
            field=models.CharField(blank=True, default='ligth', max_length=200, null=True),
        ),
    ]
