# Generated by Django 4.2.4 on 2024-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_profileclient_date_monitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='date_time_last_logger',
            field=models.DateTimeField(blank=True, max_length=800, null=True, verbose_name='Fecha/hora logger'),
        ),
    ]
