# Generated by Django 4.0.5 on 2022-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_user_is_admin_view_alter_profileclient_is_apr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondetail',
            name='flow',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='nivel',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='total',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
