# Generated by Django 4.2.4 on 2024-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_interactiondetail_date_time_last_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='file_dga',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificado DGA'),
        ),
    ]
