# Generated by Django 4.2.4 on 2024-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_profileclient_file_dga'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='date_code_dga',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha codigo creacion DGA'),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='date_report_api',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio monitoreo'),
        ),
    ]
