# Generated by Django 4.0.5 on 2022-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_interactiondetail_date_medition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondetail',
            name='date_time_medition',
            field=models.DateTimeField(blank=True, max_length=800, null=True),
        ),
    ]
