# Generated by Django 4.0.5 on 2022-07-01 04:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_interactiondetail_date_time_medition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('granted_flow', models.CharField(blank=True, max_length=1000, null=True)),
                ('well_depth', models.CharField(blank=True, max_length=1000, null=True)),
                ('static_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('dynamic_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('pump_installation_depth', models.CharField(blank=True, max_length=1000, null=True)),
                ('inside_diameter_well', models.CharField(blank=True, max_length=1000, null=True)),
                ('duct_outside_diameter', models.CharField(blank=True, max_length=1000, null=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.quotation')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('rersolution', models.CharField(blank=True, max_length=300, null=True)),
                ('standar', models.CharField(blank=True, max_length=300, null=True)),
                ('date_instalation', models.DateField(blank=True, null=True)),
                ('date_transmission', models.DateField(blank=True, null=True)),
                ('date_official', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
