# Generated by Django 4.0.5 on 2022-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_formlandingcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
