# Generated by Django 4.0.5 on 2022-07-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_quotation_is_active_quotation_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalinfo',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminView',
        ),
    ]
