# Generated by Django 4.1 on 2022-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_webinars_profilefootprints_elementsprogramation'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='link_meet',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
