# Generated by Django 4.1 on 2022-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_webinars_wallpaper_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='charge_present',
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
    ]
