# Generated by Django 4.1 on 2022-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_webinars_charge_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webinars',
            name='txt_date',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
