# Generated by Django 4.1 on 2022-08-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_webinars_description_webinars_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name_enterprise', models.CharField(blank=True, max_length=300, null=True)),
                ('address_enterprise', models.CharField(blank=True, max_length=600, null=True)),
                ('name_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('mail_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_contact', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_external_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('img_add', models.ImageField(blank=True, null=True, upload_to='upload/notes/% Y/% m/% d/')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.well')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='external_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.externalclient'),
        ),
    ]
