# Generated by Django 4.1 on 2022-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_externalclient_quotation_is_external_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='name',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
