# Generated by Django 4.1 on 2022-08-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_well_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='type_captation',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
