# Generated by Django 4.1 on 2022-08-30 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_well_type_captation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFootprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('number_module', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='activities_org_extraterritorial',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='cert_postulation',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='economic_activity',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file10',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file11',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file12',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file6',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file7',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file8',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='file9',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='mail_admin_apl_enterprise',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='mail_represent_legal',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='name_admin_apl_enterprise',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='name_represent_legal',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='phone_admin_apl_enterprise',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='phone_represent_legal',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='res_1238',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='size_company',
        ),
        migrations.AddField(
            model_name='profilefootprints',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SectionModuleFootprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('number_section', models.CharField(blank=True, max_length=12, null=True)),
                ('joined', models.BooleanField(default=False)),
                ('in_validate', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, max_length=1200, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.modulefootprints')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('comment', models.TextField(max_length=1200)),
                ('answer', models.TextField(blank=True, max_length=1200, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sectionmodulefootprints')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modulefootprints',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profilefootprints'),
        ),
        migrations.CreateModel(
            name='FieldSectionFootprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sectionmodulefootprints')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
