# Generated by Django 4.1 on 2022-08-30 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_modulefootprints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsSelectionFieldFootprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=1500)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.fieldsectionfootprints')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
