# Generated by Django 4.1 on 2022-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_fieldsectionfootprints_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsectionfootprints',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
