# Generated by Django 4.1 on 2022-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_fieldsectionfootprints_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefootprints',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
