# Generated by Django 4.1 on 2022-09-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_ticketsupport_footprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsupport',
            name='footprint',
        ),
        migrations.AddField(
            model_name='ticketsupport',
            name='footprint_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.modulefootprints'),
        ),
    ]
