# Generated by Django 4.1 on 2022-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_remove_ticketsupport_footprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsupport',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketsupport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
