# Generated by Django 4.1.1 on 2022-09-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_sectionmodulefootprints_is_file_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='code_dga_site',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
