# Generated by Django 4.1.1 on 2022-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_remove_modulefootprints_is_captation_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefootprints',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
