# Generated by Django 4.1.2 on 2022-11-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_well_exact_address_well_img1_well_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='img_add',
        ),
        migrations.AddField(
            model_name='quotation',
            name='pass_technical_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='well',
            name='has_flow_sensor',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/wells'),
        ),
        migrations.AlterField(
            model_name='well',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/wells'),
        ),
    ]
