# Generated by Django 4.1.2 on 2022-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_remove_note_img_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='duct_outside_diameter',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='dynamic_level',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='granted_flow',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='inside_diameter_well',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='pump_installation_depth',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='static_level',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_depth',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
    ]
