# Generated by Django 4.1.3 on 2022-11-22 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_variableclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableclient',
            name='type_variable',
            field=models.CharField(default=django.utils.timezone.now, max_length=1200),
            preserve_default=False,
        ),
    ]
