# Generated by Django 4.1.7 on 2023-02-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_economicactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee'),
        ),
    ]
