# Generated by Django 4.2.1 on 2023-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='latitude',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='longitude',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
