# Generated by Django 4.2.1 on 2023-05-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_sectionelement_typeelement_remove_project_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeelement',
            name='type_file',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
