# Generated by Django 4.2.1 on 2023-05-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_typeelement_type_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueelement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valueelement',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valueelement',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
