# Generated by Django 4.2.1 on 2023-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_valueelement_is_approved_valueelement_is_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valueelement',
            old_name='value_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='valueelement',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='valueelement',
            name='value_txt',
        ),
        migrations.AddField(
            model_name='valueelement',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
