# Generated by Django 4.2.1 on 2023-06-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_rename_value_file_valueelement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueelement',
            name='code',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='valueelement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
            preserve_default=False,
        ),
    ]
