# Generated by Django 4.2.4 on 2023-08-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_alter_valueelement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='client',
        ),
        migrations.RemoveField(
            model_name='action',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='action',
            name='type_action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.RemoveField(
            model_name='elementsprogramation',
            name='webinar',
        ),
        migrations.DeleteModel(
            name='FormLandingContact',
        ),
        migrations.RemoveField(
            model_name='note',
            name='well',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='external_client',
        ),
        migrations.RemoveField(
            model_name='typeelement',
            name='section',
        ),
        migrations.RemoveField(
            model_name='valueelement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='valueelement',
            name='type_element',
        ),
        migrations.RemoveField(
            model_name='valueelement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='well',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ElementsProgramation',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='SectionElement',
        ),
        migrations.DeleteModel(
            name='TypeAction',
        ),
        migrations.DeleteModel(
            name='TypeElement',
        ),
        migrations.DeleteModel(
            name='ValueElement',
        ),
        migrations.DeleteModel(
            name='Webinars',
        ),
        migrations.DeleteModel(
            name='Well',
        ),
    ]
