# Generated by Django 4.2.4 on 2023-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_remove_action_client_remove_action_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableclient',
            name='type_variable',
            field=models.CharField(choices=[('ADM', 'administrator'), ('STU', 'estudiante')], max_length=1200),
        ),
    ]
