# Generated by Django 4.2.4 on 2023-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_alter_variableclient_type_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileclient',
            name='in1',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='in2',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='in3',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='in4',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='in5',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='in6',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='others_ind',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='theme',
        ),
        migrations.AddField(
            model_name='profileclient',
            name='standard',
            field=models.CharField(blank=True, choices=[('MAYOR', 'mayor'), ('MEDIO', 'medio'), ('MENOR', 'menor'), ('CAUDALES MUY PEQUEÑOS', 'caudales_muy_pequenos')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='variableclient',
            name='type_variable',
            field=models.CharField(choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('ACUMULADO', 'acumulado')], max_length=1200),
        ),
    ]
