# Generated by Django 4.2.4 on 2023-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_remove_profileclient_in1_remove_profileclient_in2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileclient',
            old_name='is_dga',
            new_name='is_monitoring',
        ),
        migrations.RemoveField(
            model_name='profileclient',
            name='is_dga_medium',
        ),
        migrations.AddField(
            model_name='profileclient',
            name='date_delivery_act',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='date_monitoring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='date_reporting_dga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='flow_granted_dga',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='is_send_dga',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='shac',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
