# Generated by Django 4.2.4 on 2023-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_rename_is_dga_profileclient_is_monitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableclient',
            name='is_other_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variableclient',
            name='token_service',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
