# Generated by Django 4.2.4 on 2023-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_variableclient_is_other_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='is_prom_flow',
            field=models.BooleanField(default=False),
        ),
    ]
