# Generated by Django 4.2.4 on 2023-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_profileclient_is_prom_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerticket',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='answerticket',
            name='ticket_support',
        ),
        migrations.DeleteModel(
            name='EconomicActivity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='enterprise',
        ),
        migrations.DeleteModel(
            name='ExternalClient',
        ),
        migrations.RemoveField(
            model_name='fieldsectionfootprints',
            name='section',
        ),
        migrations.RemoveField(
            model_name='modulefootprints',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='optionsselectionfieldfootprints',
            name='field',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='client',
        ),
        migrations.RemoveField(
            model_name='profilefootprints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionsection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionmodulefootprints',
            name='module',
        ),
        migrations.RemoveField(
            model_name='technicalinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='footprint_module',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='support_section',
        ),
        migrations.RemoveField(
            model_name='ticketsupport',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='profileclient',
            options={'verbose_name': 'Well'},
        ),
        migrations.AddField(
            model_name='interactiondetail',
            name='is_send_dga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactiondetail',
            name='txt_error',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerTicket',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='FieldSectionFootprints',
        ),
        migrations.DeleteModel(
            name='ModuleFootprints',
        ),
        migrations.DeleteModel(
            name='OptionsSelectionFieldFootprints',
        ),
        migrations.DeleteModel(
            name='ProfileFootprints',
        ),
        migrations.DeleteModel(
            name='QuestionSection',
        ),
        migrations.DeleteModel(
            name='SectionModuleFootprints',
        ),
        migrations.DeleteModel(
            name='SupportSection',
        ),
        migrations.DeleteModel(
            name='TechnicalInfo',
        ),
        migrations.DeleteModel(
            name='TicketSupport',
        ),
    ]
