# Generated by Django 4.2.4 on 2023-08-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_remove_answerticket_administrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactiondetail',
            old_name='txt_error',
            new_name='soap_return',
        ),
    ]
