# Generated by Django 4.2.4 on 2023-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_rename_txt_error_interactiondetail_soap_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondetail',
            name='soap_return',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
