# Generated by Django 4.2.4 on 2023-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_alter_interactiondetail_soap_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='password_dga_software',
            field=models.CharField(default='ZSQgCiDg7y', max_length=1400),
        ),
        migrations.AddField(
            model_name='profileclient',
            name='rut_report_dga',
            field=models.CharField(default='17352192-8', max_length=1400),
        ),
    ]
