# Generated by Django 4.2.4 on 2023-08-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_profileclient_is_dga_alter_profileclient_is_apr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='is_thethings',
            field=models.BooleanField(default=False),
        ),
    ]
