# Generated by Django 4.2.4 on 2023-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_profileclient_is_thethings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='txt_password',
            field=models.CharField(blank=True, default='pozos.2023', max_length=1200, null=True),
        ),
    ]
