apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-api
  namespace: smarthydro
  labels:
    app: business-api
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: business-api
  template:
    metadata:
      labels:
        app: business-api
        version: v1.0.0
    spec:
      containers:
        - name: business-api
          image: smarthydro/business-api:latest
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: REDIS_URL
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarthydro-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarthydro-secrets
                  key: REDIS_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: smarthydro-secrets
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: JWT_ALGORITHM
            - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: LOG_LEVEL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: ENVIRONMENT
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: smarthydro-config
                  key: DEBUG
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: business-api-service
  namespace: smarthydro
spec:
  selector:
    app: business-api
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
