# Generated by Django 5.0.2 on 2024-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='counter_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
