# Generated by Django 5.0.2 on 2024-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_profileclient_counter_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileclient',
            name='counter_total',
        ),
        migrations.AddField(
            model_name='variableclient',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
