# Generated by Django 5.0.2 on 2024-02-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_profileclient_counter_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableclient',
            name='counter',
        ),
    ]
