# Generated by Django 5.0.2 on 2024-02-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_variableclient_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableclient',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
