# Generated by Django 5.0.2 on 2024-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_variableclient_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileclient',
            name='frecuency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
