# Generated by Django 5.0.2 on 2024-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_profileclient_frecuency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='frecuency',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
