# Generated by Django 5.1.6 on 2025-02-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerpersons',
            options={'verbose_name': 'Persona registrada', 'verbose_name_plural': 'Personas registradas'},
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='flow_granted_dga',
            field=models.FloatField(blank=True, max_length=1200, null=True, verbose_name='Caudal otorgado(lt/s)'),
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='name_informant',
            field=models.CharField(default='Diego Mardones', max_length=1200, verbose_name='Nombre informante'),
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='send_dga',
            field=models.BooleanField(default=False, verbose_name='Activar cumplimiento'),
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='standard',
            field=models.CharField(choices=[('SIN_ESTANDAR', 'sin estandar'), ('MAYOR', 'mayor'), ('MEDIO', 'medio'), ('MENOR', 'menor'), ('CAUDALES_MUY_PEQUENOS', 'cmp')], default='SIN_ESTANDAR', max_length=300, verbose_name='Estandar'),
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='total_granted_dga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Totalizado otorgado(m3)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d1',
            field=models.FloatField(default=0.0, verbose_name='Profundidad(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d2',
            field=models.FloatField(default=0.0, verbose_name='Posicionamiento de bomba(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d3',
            field=models.FloatField(default=0.0, verbose_name='Posicionamiento nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d4',
            field=models.FloatField(default=0.0, verbose_name='Diametro ducto salida bomba(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d5',
            field=models.FloatField(default=0.0, verbose_name='Diametro flujometro(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_config_profiles', to='core.catchmentpoint', verbose_name='Punto de captacion'),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ikolu_profiles', to='core.catchmentpoint', verbose_name='Punto de captacion'),
        ),
    ]
