# Generated by Django 5.1.6 on 2025-02-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registerpersons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecatchment',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='point_catchment',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='ikolu_profiles', to='core.catchmentpoint', verbose_name='Punto de captacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemescatchment',
            name='points_catchment',
            field=models.ManyToManyField(blank=True, related_name='schemes', to='core.catchmentpoint', verbose_name='Punto de captacion'),
        ),
    ]
