# Generated by Django 5.1.6 on 2025-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filecatchment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationscatchment',
            name='type_alert',
            field=models.CharField(blank=True, choices=[('MAX', 'mas'), ('MIN', 'menos'), ('EQUALS', 'igual')], max_length=300, null=True, verbose_name='Tipo de alerta'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='type_variable',
            field=models.CharField(blank=True, choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('CAUDAL PROMEDIO', 'caudal_promedio((diff/3600)*1000)'), ('TOTALIZADO', 'totalizado')], max_length=300, null=True, verbose_name='Tipo variable'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='send_dga',
            field=models.BooleanField(default=False, verbose_name='Agregar a la cola DGA'),
        ),
    ]
