# Generated by Django 5.1.5 on 2025-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationscatchment_type_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='pulses',
            field=models.IntegerField(default=0, verbose_name='Pulsos'),
        ),
    ]
