# Generated by Django 5.1.5 on 2025-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interactiondetail_pulses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Profundidad(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Posicionamiento de bomba(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Posicionamiento nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diametro ducto salida bomba(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diametro flujometro(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nuevo campo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type_variable',
            field=models.CharField(choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('CAUDAL_PROMEDIO', 'caudal_promedio((diff/3600)*1000)'), ('TOTALIZADO', 'totalizado')], max_length=1200, verbose_name='Tipo variable'),
        ),
    ]
