# Generated by Django 5.1.5 on 2025-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profiledataconfigcatchment_d1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='flow_granted_dga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, max_length=1200, verbose_name='Caudal otorgado(lt/s)'),
        ),
    ]
