# Generated by Django 5.1.6 on 2025-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dgadataconfigcatchment_flow_granted_dga'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='days_not_conection',
            field=models.IntegerField(default=0, verbose_name='Dias sin conexión'),
        ),
    ]
