# Generated by Django 5.1.6 on 2025-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_interactiondetail_days_not_conection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactiondetail',
            options={'verbose_name': 'Telemetria', 'verbose_name_plural': 'Registros Telemetria'},
        ),
        migrations.RemoveField(
            model_name='interactiondetail',
            name='is_warning',
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='flow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caudal(lt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='nivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='water_table',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nivel freático(mt)'),
        ),
    ]
