# Generated by Django 5.1.6 on 2025-02-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interactiondetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='frecuency',
            field=models.CharField(blank=True, choices=[('1', '1 minuto'), ('5', '5 minutos'), ('60', '60 minutos')], max_length=300, null=True, verbose_name='Frecuencia'),
        ),
    ]
