# Generated by Django 5.1.6 on 2025-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_catchmentpoint_frecuency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d6',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Caudalimetro inicial'),
        ),
    ]
