# Generated by Django 5.1.6 on 2025-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profiledataconfigcatchment_d6'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationscatchment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_periodic',
            field=models.BooleanField(default=False, verbose_name='Cada registro'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_response',
            field=models.BooleanField(default=False, verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='is_wait',
            field=models.BooleanField(default=False, verbose_name='Espera'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
    ]
