# Generated by Django 5.1.6 on 2025-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificationscatchment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationscatchment',
            name='type_variable',
            field=models.CharField(blank=True, choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('CAUDAL PROMEDIO', 'caudal_promedio((diff/3600)*1000)'), ('TOTALIZADO', 'totalizado'), ('TODOS', 'todos')], max_length=300, null=True, verbose_name='Tipo variable'),
        ),
    ]
