# Generated by Django 5.1.6 on 2025-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificationscatchment_type_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationscatchment',
            name='message',
            field=models.CharField(max_length=1300, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='responsenotificationscatchment',
            name='response',
            field=models.CharField(max_length=1300, verbose_name='Respuesta'),
        ),
    ]
