# Generated by Django 5.1.6 on 2025-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notificationscatchment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='lat',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='lon',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='longitud'),
        ),
    ]
