# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_catchmentpoint_lat_catchmentpoint_lon'),
    ]

    operations = [
        # Agregar campos optimizados para telemetría
        migrations.AddField(
            model_name='catchmentpoint',
            name='is_telemetry_active',
            field=models.BooleanField(default=False, verbose_name='Telemetría activa'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='telemetry_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio telemetría'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='active_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proveedor activo'),
        ),
        
        # Cambiar coordenadas de CharField a DecimalField
        migrations.RenameField(
            model_name='catchmentpoint',
            old_name='lat',
            new_name='latitude_old',
        ),
        migrations.RenameField(
            model_name='catchmentpoint',
            old_name='lon',
            new_name='longitude_old',
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, verbose_name='Ubicación'),
        ),
        
        # Agregar índices para optimizar consultas
        migrations.AddIndex(
            model_name='catchmentpoint',
            index=models.Index(fields=['is_telemetry_active', 'active_provider'], name='core_catchm_is_tele_8f2c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='catchmentpoint',
            index=models.Index(fields=['frecuency', 'is_telemetry_active'], name='core_catchm_frecuen_9a8b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='catchmentpoint',
            index=models.Index(fields=['project', 'is_telemetry_active'], name='core_catchm_project_1a2b3c_idx'),
        ),
        
        # Corregir tipos de datos en ProfileDataConfigCatchment
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Profundidad(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Posicionamiento de bomba(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Posicionamiento nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Diametro ducto salida bomba(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Diametro flujometro(pulg)'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Caudalimetro inicial'),
        ),
        
        # Corregir tipos de datos en DgaDataConfigCatchment
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='flow_granted_dga',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Caudal otorgado(lt/s)'),
        ),
        
        # Corregir campo en Variable
        migrations.AlterField(
            model_name='variable',
            name='calculate_nivel',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Calcular nivel (solo aplica en nivel)'),
        ),
    ] 